# The Homogenous Systems
---
- In previous discussion we have tackled systems of linear equations that can have either one of the following:
    1. A unique solution
    2. Infinitely many solutions
    3. No solutions or inconsistent.
    
- There are systems of linear equations that have atleast one solutions, and these are called homogenous systems.
- In a homogenous system, the constant term is zero.
- Therefore the augemented matrix of a homogenous system is $[\textbf{A}|0]$.
#### Example
---
$
\begin{equation}
2x+3y-z= 0 \\
-x+5y+2z = 0 \\
\end{equation}$


In [9]:
# Pythonic Solutions
# the following functions are the steps involved in forward elimination
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

# <font color = red> ASSIGNMENT 1</font>
- The above python functions are developed to automate forward elimination.
- To complete the process of determining the solution, create a function or steps of function that will automate backward substitution.

In [1]:
import numpy as np
A = np.array([[1,-1,1,3],[0,1,2,4],[0,0,1,2],[0,0,0,0],[0,0,0,0]]) 

def backwardsub(A):
    m, n = A.shape  

    while m > 0 and np.all(A[m-1, n-2:] == 0):
        m -= 1

    if m == 0:
        return "No Solution..."
    elif n - 1 > m:
        return "Tnfinite Solutions..."

    sol = np.zeros(m)

    for x in range(m - 1, -1, -1):
        coefficients = A[x, :-1]
        constant = A[x, -1]

        if np.all(coefficients == 0):
            return "No Unique Solution..."

        r = np.dot(sol, coefficients)
        sol[x] = (constant - r) / coefficients[x]

    return sol

result = backwardsub(A)
print(result)

[1. 0. 2.]


# More Examples
---
Solve the equation
$
\begin{equation}
x_1-x_2+x_3=3 \\
2x_1+x_2+8x_3 = 18 \\
4x_1+2x_2-3x_3 = -2 \\
\end{equation}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    2 & 1 & 8 &\bigm| & 18 \\
    4 & 2 & -3 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    4 & 2 & -3 &\bigm| & -2 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    4 & 2 & -3 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 4\text{R}_{1}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    0 & 6 & -7 &\bigm| & -14 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    0 & 6 & -7 &\bigm| & -14 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3}-2\text{R}_{2}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    0 & 0 & -19 &\bigm| & -38 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    0 & 0 & -19 &\bigm| & -38 \\
\end{pmatrix}
\xrightarrow{\frac{1}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 1 & 2 &\bigm| & 4 \\
    0 & 0 & -19 &\bigm| & -38 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 1 & 2 &\bigm| & 4 \\
    0 & 0 & -19 &\bigm| & -38 \\
\end{pmatrix}
\xrightarrow{\frac{-1}{19}\text{R}_{3}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 1 & 2 &\bigm| & 4 \\
    0 & 0 & 1 &\bigm| & 2 \\
\end{pmatrix}
$
<br><br>
The system of equation has the solution:
$
\begin{equation}
x_1-x_2+x_3=3 \\
x_2+2x_3 = 4 \\
x_3 = 2 \\
\end{equation}
$
<br>
Performing back substitution yields:
$
\begin{equation}
x_1-x_2+x_3=3 \to x_1-0+2 = 3 \to x_1 = 3-2 = 1 \\
x_2+2x_3 = 4 \to x_2+2(2)=4 \to x_2+4=4 \to x_2 = 4-4 =0 \\
x_3 = 2 \\
\end{equation}
$
<br>
$\therefore \ x_1=1, x_2=0, x_3=2$

In [21]:
# using pythonic solutions
import numpy as np
A=np.array([[1,-1,1,3],[2,1,8,18],[4,2,-3,-2]])

## Add -2 times row 0 to row 1
A1 = RowAdd(A,0,1,-2)
print("A1")
print(A1,'\n')

## Add -4 times row 0 to row 2
A2 = RowAdd(A1,0,2,-4)
print("A2")
print(A2,'\n')

## Add -2 times row 1 to row 2
A3 = RowAdd(A2,1,2,-2)
print("A3")
print(A3,'\n')

## Multiply row 1 by 1/3
A4 = RowScale(A3,1,1.0/3)
print("A4")
print(A4,'\n')

## Multiply row 2 by 1/19
A5 = RowScale(A4,2,1.0/-19.)
print("A5")
print(A5,'\n')
print("Use your assignment for the backward substitution to find the solutions.")

A1
[[ 1. -1.  1.  3.]
 [ 0.  3.  6. 12.]
 [ 4.  2. -3. -2.]] 

A2
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   6.  -7. -14.]] 

A3
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   0. -19. -38.]] 

A4
[[  1.  -1.   1.   3.]
 [  0.   1.   2.   4.]
 [  0.   0. -19. -38.]] 

A5
[[ 1. -1.  1.  3.]
 [ 0.  1.  2.  4.]
 [-0. -0.  1.  2.]] 

Use your assignment for the backward substitution to find the solutions.


# Spanning Sets
---
- Recall that the linear equation has the form:
$a_1x_1+a_2x_2+...+a_nx_n=b$
- If we let $a_1,a_2,...,a_n$ be vectors, and $b$ is also a vector of the same size as the $a_1,a_2,...,a_n$.
- If we denotes $\{a_1,a_2,...,a_n\}$ as a set of vectors $\in \mathbb{R}^n$, then any linear combination of $\{a_1,a_2,...,a_n\}$ is called a **span** of $x_1,x_2,...,x_n$, which is denoted by $span(a_1,a_2,...,a_n)$
- If $span(a_1,a_2,...,a_n) \in \mathbb{R}^n$, then it is called the *spanning set* for $\mathbb{R}^n$.
#### Example:
Show that
\begin{pmatrix}
    \begin{bmatrix} 2 \\ -1 \end{bmatrix} \ 
    \begin{bmatrix} 1 \\ 3 \end{bmatrix}\\
\end{pmatrix}
is a span.<br>
Solution:
1. Write the span in terms of a linear equation:
\begin{equation}
    \textbf{x}\begin{bmatrix} 2 \\ -1 \end{bmatrix} \ +
    \textbf{y}\begin{bmatrix} 1 \\ 3 \end{bmatrix} \ =
    \begin{bmatrix} a \\ b \end{bmatrix} \\
\end{equation}
2. Transform the linear equation into its reduved echelon form:
$
\begin{pmatrix}
    2 & 1 &\bigm| & a \\
    -1 & 3 &\bigm| & b \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} \leftrightarrow \text{R}_{2}}
\begin{pmatrix}
    -1 & 3 &\bigm| & b \\
    2 & 1 &\bigm| & a \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    -1 & 3 &\bigm| & b \\
    2 & 1 &\bigm| & a \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} 2+ \text{R}_{1}}
\begin{pmatrix}
    -1 & 3 &\bigm| & b \\
    0 & 7 &\bigm| & a+2b \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    -1 & 3 &\bigm| & b \\
    0 & 7 &\bigm| & a+2b \\
\end{pmatrix}
\xrightarrow{\frac{1}{7} \text{R}_{2}}
\begin{pmatrix}
    -1 & 3 &\bigm| & b \\
    0 & 1 &\bigm| & \frac{a+2b}{7} \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    -1 & 3 &\bigm| & b \\
    0 & 1 &\bigm| & \frac{a+2b}{7} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1}-3 \text{R}_{2}}
\begin{pmatrix}
    -1 & 0 &\bigm| & \frac{b+3a}{7} \\
    0 & 1 &\bigm| & \frac{a+2b}{7} \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    -1 & 0 &\bigm| & \frac{b+3a}{7} \\
    0 & 1 &\bigm| & \frac{a+2b}{7} \\
\end{pmatrix}
\xrightarrow{(-1)\text{R}_{1}}
\begin{pmatrix}
    1 & 0 &\bigm| & -\frac{b+3a}{7} \\
    0 & 1 &\bigm| & \frac{a+2b}{7} \\
\end{pmatrix}
$
<br><br>
- The final reduced row echelon is of the form:
$
\begin{pmatrix}
    -1 & 0 &\bigm| & \frac{b+3a}{7} \\
    0 & 1 &\bigm| & \frac{a+2b}{7} \\
\end{pmatrix}
\xrightarrow{(-1)\text{R}_{1}}
\begin{pmatrix}
    1 & 0 &\bigm| & -\frac{b+3a}{7} \\
    0 & 1 &\bigm| & \frac{a+2b}{7} \\
\end{pmatrix}
$
<br><br>
$\therefore$ it is a span

# <font color = red> Assignment 2 </font>
---
**INSTRUCTION**
- Use latex programming to show your manual solutions.
- If the problem involves determining the row echelon or reduced row echelon, show both the manual and the pythonic solutions.
- Solutions must be saved as a jupyter notebook.
- Push your solutions to your forked github repo.
- Note that there is some **possibility** that some ,or all, of your exam questions will be taken from these assignment.
- The technique here is to first solve manually before writing in Latex.
---


1. Provide reasons why each of the following equations is, or is not, a linear equation.
- $\cos{\theta}x+4y+z = \sqrt{3}$
<br>Ans: This equation is a linear equation as it can be written as $a_1x_1+a_2x_2+...+a_nx_n = b$
- $cos{x}4y+z = \sqrt{3}$
<br>Ans: This equation is not a linear equation because $cos{x}4y$ isn't divisible by constants
- $x^{-1}+7y+z = \sin{(\frac{\pi}{2})}$
<br>Ans: This equation is not a linear equation because a term has an exponent of -1
- $x^1+y^1+z^1=0$
<br>Ans: This equation is a linear equation as it can be written as $a_1x_1+a_2x_2+...+a_nx_n = b$, and the exponents are divisible by constants and raised to 1


2. Find the solutions to the linear equations:
- $2x_1+3x_2 =5$
Ans:<br>
-> $2x_1 = 5 - 3x_2$<br>
-> $x_1 = \frac{5}{2} - \frac{3}{2}x_2$<br>
-> $x_2 = \frac{5}{3} - \frac{2}{3}x_1$<br><br>
- $4x_1+3x_2+2x_3=1$
Ans:<br>
-> $x_1 = \frac{1}{4} - \frac{3}{4}x_2 - \frac{1}{2}x_3$ <br>
-> $x_2 = \frac{1}{3} - \frac{4}{3}x_1 - \frac{2}{3}x_3$ <br>
-> $x_3 = \frac{1}{2} - \frac{3}{2}x_2 - 2x_1$ <br><br>
- $3x-6y=0$
Ans:<br>
-> $3x = 6y$ <br>
-> $x = 2y$<br>
-> $\frac{1}{2}x = y$<br>
---


3. Solve the following systems of linear equations<br>
a.<br> 
\begin{equation}
x-y=0 
\end{equation}
<br>
\begin{equation}
2x+y = 3
\end{equation}

b. <br>
\begin{equation}
x+5y= -1
\end{equation}
<br>
\begin{equation}
-x+y = -5 
\end{equation}
<br>
\begin{equation}
2x+4y = 4
\end{equation}

c. <br>
\begin{equation}
2x_1+3x_2-x_3= -1 \\
\end{equation}

\begin{equation}
x_1+x_3 = 0 \\
\end{equation}

\begin{equation}
-x_1+2x_2-2x_3 = 0 \\
\end{equation}
<br>


Manual Solutions: <br>
a. 
<br>
$
\begin{pmatrix}
    1 & -1 &\bigm| & 0 \\
    2 & 1 &\bigm| & 3 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & -1 &\bigm| & 0 \\
    0 & 3 &\bigm| & 3 \\
\end{pmatrix}
\xrightarrow{\frac{1}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & -1 &\bigm| & 0 \\
    0 & 1 &\bigm| & 1 \\
\end{pmatrix}
$
<br><br>
From the resulting augmented matrix, <br>
\begin{equation} 
x - y = 0, y = 1 
\end{equation}
<br>
Performing back substitution, <br>
\begin{equation}
x - 1 = 0 \rightarrow x = 1 ; y = 1
\end{equation}
<br>
The solution is = <br>
\begin{pmatrix}
    1 \\
    1 \\
\end{pmatrix}
<br><br>
b. 
<br><br>
$$
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    -1 & 1 &\bigm| & -5 \\
    2 & 4 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6 &\bigm| & -6 \\
    2 & 4 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 2\text{R}_{1}}
$$
$$
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6 &\bigm| & -6 \\
    0 & -6 &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6 &\bigm| & -6 \\
    0 & 0 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{1}{6}\text{R}_{2}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    0 & 0 &\bigm| & 0 \\
\end{pmatrix}
$$
<br><br>
From the resulting augmented matrix, <br>
\begin{equation} 
 x + 5y = -1 ; y = -1
\end{equation}
<br>
Performing back substitution, <br>
\begin{equation}
x +5y = -1 \rightarrow x + 5(-1) = -1 \\
\rightarrow x - 5 = -1 \\
\rightarrow x = 4 ; y = -1 \\
\end{equation}
<br>
The solution is = <br>
\begin{pmatrix}
    4 \\
    -1 \\
\end{pmatrix}
<br><br>
c. 
<br><br>
$$
\begin{pmatrix}
    2 & 3 & -1 &\bigm| & -1 \\
    1 & 0 & 1 &\bigm| & 0 \\
    -1 & 2 & -2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + 2\text{R}_{2}}
\begin{pmatrix}
    0 & 3 & -3 &\bigm| & -1 \\
    1 & 0 & 1 &\bigm| & 0 \\
    -1 & 2 & -2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
$$
$$
\begin{pmatrix}
    0 & 3 & -3 &\bigm| & -1 \\
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 2 & -1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{3}}
\begin{pmatrix}
    0 & 1 & -2 &\bigm| & -1 \\
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 2 & -1 &\bigm| & 0 \\
\end{pmatrix} \
\xrightarrow{\text{R}_{3} - 2\text{R}_{1}}
$$
$$
\begin{pmatrix}
    0 & 1 & -2 &\bigm| & -1 \\
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 0 & 3 &\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{\frac{1}{3}\text{R}_{3}}
\begin{pmatrix}
    0 & 1 & -2 &\bigm| & -1 \\
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 0 & 1 &\bigm| & \frac{2}{3} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} \leftrightarrow \text{R}_{2}}
$$
$$
\begin{pmatrix}
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 1 & -2 &\bigm| & -1 \\
    0 & 0 & 1 &\bigm| & \frac{2}{3} \\
\end{pmatrix}

$$
<br><br>

From the resulting augmented matrix, <br>
\begin{equation} 
x_1 + x_3 = 0 ;\\ x_2 - 2x_3 = -1 ;\\ x_3 = \frac{2}{3} 
\end{equation}
<br>
Performing back substitution, <br>
\begin{equation}
x_1 + x_3 = 0 \rightarrow x_1 + \frac{2}{3} = 0 \rightarrow x_1 = -\frac{2}{3} \\
\end{equation}
<br>
\begin{equation}
x_2 - 2x_3 = -1 \rightarrow x_2 - 2\frac{2}{3} = -1 \rightarrow x_2 - \frac{4}{3} = -1 \rightarrow x_2 = \frac{4}{3} -1 \rightarrow x_2 = \frac{1}{3}
\end{equation}
<br>
The solution is = <br>
\begin{pmatrix}
    -\frac{2}{3} \\
    \frac{1}{3} \\
    \frac{2}{3} \\
\end{pmatrix}


In [ ]:
# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def SwapRow(X,k,l):

    cols = X.shape[1] 
    
    Y = np.copy(X).astype('float64')
        
    for j in range(cols):
        temp = Y[k][j]
        Y[k][j] = Y[l][j]
        Y[l][j] = temp
        
    return Y

def ScaleRow(X,k,scale):

    rowa = X.shape[0] 
    cols = X.shape[1]  
    
    Y = np.copy(A).astype('float64')

    for j in range(cols):
        Y[k][j] *= scale
        
    return Y

def AddRow(X,k,l,scale):
    rows = X.shape[0] 
    cols = X.shape[1] 
    
    Y = np.copy(A).astype('float64')
        
    for j in range(cols):
        Y[l][j] += Y[k][j]*scale
        
    return Y


---

4. Provide reasons why the given matrices are either a row echelon, a reduced row echelon, or niether both.<br>
a. <br>
\begin{pmatrix}
   1 & 0 & 1 \\
   0 & 0 & 3 \\
   0 & 1 & 0 \\
\end{pmatrix}<br><br>
b. <br>
\begin{pmatrix}
   7 & 0 & 1 & 0 \\
   0 & 1 & -1 & 4 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}<br><br>
c. <br>
\begin{pmatrix}
   0 & 1 & 3 & 0 \\
   0 & 0 & 0 & 1 \\
\end{pmatrix}<br><br>
d. <br>
\begin{pmatrix}
   0 & 0 & 0 \\
   0 & 0 & 0 \\
   0 & 0 & 0 \\
\end{pmatrix}<br><br>
e. <br>
\begin{pmatrix}
   1 & 0 & 3 & -4 & 0 \\
   0 & 0 & 0 & 0 & 0 \\
   0 & 1 & 5 & 0 & 1 \\
\end{pmatrix}<br><br>
f. <br>
\begin{pmatrix}
   0 & 0 & 1 \\
   0 & 1 & 0 \\
   1 & 0 & 0 \\
\end{pmatrix}<br><br>
g. <br>
\begin{pmatrix}
   1 & 2 & 3 \\
   1 & 0 & 0 \\
   0 & 1 & 1 \\
   0 & 0 & 1 \\
\end{pmatrix}<br><br>
h. <br>
\begin{pmatrix}
   2 & 1 & 3 & 5 \\
   0 & 0 & 1 & -1 \\
   0 & 0 & 0 & 3 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}
<br><br>



a. This matrix is neither a reduced echelon or a row echelon, because it doesn't satisfy the conditions of Row 2's leading entry not being in a column to left of the leading entry of Row 1, and the Row 2's leading entry is not 1, so it is not a reduced echelon. <br>

b. This matrix is only a row echelon, because it satisfies both conditions of rows with majority zeroes are at the bottom, and that the leading entries are in a column to the left of the leading entry before it. But it is not a reduced row echelon because the leading entry of Row 1 is not 1. <br>

c. It is a row echelon, since the rows with majority are at the bottom part>

d. It is neither because this matrix contains only zeroes. <br>

e. It is neither, because it is does not satisfy the condition of the rows with majority zeroes being at the bottom, and even though all leading entries are 1, if it does not satisfy the conditions of a row echelon, it can not be considered a reduced row echelon. <br>

f. It is neither, because it does not satisfy the conditions that the leading entry (i.e., the leftmost nonzero entry) of each nonzero row is 1 and that each leading entry of a row is to the right of the leading entry of the row above it. <br>

g. Neither, because the leading entry of Row 2 is not to the left of the leading entry of Row 1. <br>

h. It is only a row echelon, because the rows with majoirty zeroes are a the bottom, and that the leading entry of each row is to the right of the leading entry before it.  <br>
---

5. Solve the following systems of linear equations<br>
a.<br> 
$\begin{equation}
x_1+2x_2-3x_3=9 \\
2x_1-x_2-x_3=0 \\
4x_1-x_2+x_3=4 \\
\end{equation}$
<br>
<br>
b. <br>
$\begin{equation}
x+2y= -1 \\
2x+y+z = 1 \\
-x+y-z = -1
\end{equation}$
c. <br>
$\begin{equation}
x_1-3x_2-2x_3=0 \\
-x_1+2x_2+x_3=0 \\
2x_1+4x_2+6x_3=0 \\
\end{equation}$
<br>
d. <br>
$\begin{equation}
w+x+2y+z=1 \\
w-x-y+z=0 \\
x+y=1 \\
w+x+z=2
\end{equation}$
<br>



$a.$<br> 
$\begin{equation}
x_1+2x_2-3x_3=9 \\
2x_1-x_2-x_3=0 \\
4x_1-x_2+x_3=4 \\
\end{equation}
$
<br>
$
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    2 & -1 & -1 &\bigm| & 0 \\
    4 & -1 & 1 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & -5 & 5 &\bigm| & 0 \\
    4 & -1 & 1 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 4\text{R}_{1}}
$
<br><br>
$
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & -5 & 5 &\bigm| & 0 \\
    0 & -9 & 13 &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \frac{9}{5}\text{R}_{2}}
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & -5 & 5 &\bigm| & 0 \\
    0 & 0 & 4 &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \frac{4}{5}\text{R}_{3}}
$
<br><br>
$
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & -5 & 0 &\bigm| & \frac{-128}{5} \\
    0 & 0 & 4 &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \frac{4}{3}\text{R}_{3}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & 9-\frac{-128}{5} \\
    0 & -5 & 0 &\bigm| & \frac{-128}{5} \\
    0 & 0 & 4 &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + \frac{2}{5}\text{R}_{2}}
$
<br><br>
$
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & 9-\frac{-128}{5} \\
    0 & -5 & 0 &\bigm| & \frac{-128}{5} \\
    0 & 0 & 4 &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{-\frac{1}{5}\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & 9-\frac{-128}{5} \\
    0 & 1 & 0 &\bigm| & -\frac{-128}{25} \\
    0 & 0 & 4 &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{\frac{1}{4}\text{R}_{3}}
$
<br><br>
$
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & 9-\frac{-128}{5} \\
    0 & 1 & 0 &\bigm| & -\frac{-128}{25} \\
    0 & 0 & 1 &\bigm| & -8 \\
\end{pmatrix}
\xrightarrow{\frac{1}{4}\text{R}_{3}}
$ 
<br>
<br>
$b.$
<br>
$
\begin{equation}
x+2y= -1 \\
2x+y+z = 1 \\
-x+y-z = -1
\end{equation} <br>
$
<br><br>
$
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    2 & 1 & 1 &\bigm| & 1 \\
    -1 & 1 & -1 &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{3}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    1 & 2 & 0 &\bigm| & 0 \\
    -1 & 1 & -1 &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
$
<br><br>
$
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & 0 & 0 &\bigm| & 1 \\
    -1 & 1 & -1 &\bigm| & -1 \\
\end{pmatrix}
$
<br><br>
$
\text{There is no consistancy}
$ <br><br>
$c.$ <br>
$
\begin{equation}
x_1-3x_2-2x_3=0 \\
-x_1+2x_2+x_3=0 \\
2x_1+4x_2+6x_3=0 \\
\end{equation}
<br>
$
<br><br>
$
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    -1 & 2 & 1 &\bigm| & 0 \\
    2 & 4 & 6 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1 &\bigm| & 0 \\
    2 & 4 & 6 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 2\text{R}_{1}}
$
<br><br>
$
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1 &\bigm| & 0 \\
    0 & 10 & 10 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + 10\text{R}_{2}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1 &\bigm| & 0 \\
    0 & 0 & 0 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 3\text{R}_{2}}
$
<br><br>
$
\begin{pmatrix}
    1 & 0 & 1 &\bigm| & 0 \\
    0 & -1 & -1 &\bigm| & 0 \\
    0 & 0 & 0 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{+1\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
From the resulting augmented matrix, <br>
$
\begin{equation} 
x_1 + x_3 = 0; x_2 + x_3 = 0
\end{equation}
$
<br>
Performing back substitution, <br>
$
\begin{equation}
x_1 + x_3 = 0 \rightarrow x_1 = - x_3
\end{equation}
$
<br>
$
\begin{equation}
x_2 + x_3 = 0 \rightarrow x_2 = -x_3
\end{equation}
$
<br>
The solution is = <br> 

$x_3$ can take any real value, and $x_1$ and $x_2$ are dependent on $x_3$. $x_3 \forall \text{t} \in \mathbb{R} $ 
<br>
$
\begin{pmatrix}
    -x_3 \\
    -x_3 \\
     t \\
\end{pmatrix}
$

$d.$
<br>
$
\begin{equation}
w+x+2y+z=1 \\
w-x-y+z=0 \\
x+y=1 \\
w+x+z=2
\end{equation}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 1 & 2 & 1 &\bigm| & 1 \\
    1 & -1 & -1 & 1 &\bigm| & 0 \\
    0 & 1 & 1 & 0 &\bigm| & 1 \\
    1 & 1 & 0 & 1 &\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & 1 & 2 & 1 &\bigm| & 1 \\
    0 & -2 & -3 & 0 &\bigm| & -1 \\
    0 & 1 & 1 & 0 &\bigm| & 1 \\
    1 & 1 & 0 & 1 &\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + 3\text{R}_{3}}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 1 & 2 & 1 &\bigm| & 1 \\
    0 & 1 & 0 & 0 &\bigm| & 2 \\
    0 & 1 & 1 & 0 &\bigm| & 1 \\
    1 & 1 & 0 & 1 &\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{4} - \text{R}_{2}}{\text{R}_{3} - \text{R}_{2}}
\begin{pmatrix}
    1 & 1 & 2 & 1 &\bigm| & 1 \\
    0 & 1 & 0 & 0 &\bigm| & 2 \\
    0 & 1 & 1 & 0 &\bigm| & 1 \\
    0 & 0 & -2 & 0 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 1 & 2 & 1 &\bigm| & 1 \\
    0 & 1 & 0 & 0 &\bigm| & 2 \\
    0 & 0 & 1 & 0 &\bigm| & -1 \\
    0 & 0 & -2 & 0 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{4} + 2\text{R}_{3}}
\begin{pmatrix}
    1 & 1 & 2 & 1 &\bigm| & 1 \\
    0 & 1 & 0 & 0 &\bigm| & 2 \\
    0 & 0 & 1 & 0 &\bigm| & -1 \\
    0 & 0 & 0 & 0 &\bigm| & -1 \\
\end{pmatrix}
$
<br>
<br>
$
\textbf{No solution, because of the inconsistency}
$

6. Determine if the vectors are linear combinations<br>
a. <br>
$ \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} -1 \\ 3 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 2 \\ -6 \end{bmatrix}\\
\end{equation}$
<br><br>
b. <br>
$ \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}$
<br><br>
c. <br>
$ \begin{equation}
    \textbf{v} = \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}$
<br><br>



$\textbf{A.)}$ <br>
a. Transform it into the form u_1 + u_2 + u_3 = v <br>
b. Transform it into a linear equation <br><br>
$
     \begin{bmatrix} -1 \\ 3 \end{bmatrix} \textbf{x} +
    \begin{bmatrix} 2 \\ -6 \end{bmatrix}y =
    \begin{bmatrix} 1 \\ 2 \end{bmatrix} \\
$
<br><br>
c. Solve the system: <br>
    -x + 3y = 1 <br>
    2x - 6y = 2 <br>
d. Transform the system into an augmented matrix, then transform it into a reduced row echelon. <br><br>
$
\begin{pmatrix}
    -1 & 2  &\bigm| & 1 \\
    3 & -6 &\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + 2\text{R}_{1}}
\begin{pmatrix}
    -1 & 2  &\bigm| & 1 \\
    0 & 0 &\bigm| & 4 \\
\end{pmatrix}
\textbf{These vectors are not linear combinations}
$ <br><br>
$\textbf{B.)}$ <br>
a. Transform it into the form u_1 + u_2 + u_3 = v <br>
b. Transform it into a linear equation <br><br>
$
     \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} \textbf{x} +
    \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}y =
    \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \\
$
<br><br>
c. Solve the system: <br>
    x = 1 <br>
    x + y = 2 <br>
    y = 3 <br>
d. Transform the system into an augmented matrix, then transform it into a reduced row echelon. <br><br>
$
\begin{pmatrix}
    1 & 0  &\bigm| & 1 \\
    1 & 1  &\bigm| & 2 \\
    0 & 1  &\bigm| & 3 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & 0  &\bigm| & 1 \\
    0 & 1  &\bigm| & 1 \\
    0 & 1  &\bigm| & 3 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0  &\bigm| & 1 \\
    0 & 1  &\bigm| & 1 \\
    0 & 0  &\bigm| & 2 \\
\end{pmatrix}
\textbf{These vector is not a linear combination}
$ <br><br>
$\textbf{C.)}$ <br>
a. Transform it into the form u_1 + u_2 + u_3 = v <br>
b. Transform it into a linear equation <br><br>
$
     \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} \textbf{x} +
    \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}y =
    \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix} \\
$
<br><br>
c. Solve the system: <br>
    x = 3 <br>
    x + y = 1 <br>
    y = -2 <br>
d. Transform the system into an augmented matrix, then transform it into a reduced row echelon. <br><br>
$
\begin{pmatrix}
    1 & 0  &\bigm| & 3 \\
    1 & 1  &\bigm| & 1 \\
    0 & 1  &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & 0  &\bigm| & 3 \\
    0 & 1  &\bigm| & -2 \\
    0 & 1  &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0  &\bigm| & 3 \\
    0 & 1  &\bigm| & -2 \\
    0 & 0  &\bigm| & 0 \\
\end{pmatrix}
$
e. Plug the values into the linear combination <br>
$
     \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} \textbf{3} +
    \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix} \textbf{-2} =
    \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix} \\
$
Therefrore, the vectors are a linear combination of each other.
 <br><br>

---

7. Show that the following vectors are a span: <br>
a.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 1 \\ \end{bmatrix}
\begin{bmatrix}1 \\ -1 \\ \end{bmatrix}
\end{pmatrix}
$
<br><br>
b.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br><br>
c.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br><br>

7. <br>
 a.)<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 1 \\ \end{bmatrix}
\begin{bmatrix}1 \\ -1 \\ \end{bmatrix}
\end{pmatrix}
$
<br><br> 1.)<br><br>
$
\textbf{x} \begin{bmatrix} 1 \\ 1 \end{bmatrix} +
\textbf{y} \begin{bmatrix} 1 \\ -1 \end{bmatrix}  =
\begin{bmatrix} a \\ b \end{bmatrix} \\
$
<br><br> 2.) <br><br>
$
    \begin{pmatrix}
    1 & 1  &\bigm| & a \\
    1 & -1  &\bigm| & b \\
    \end{pmatrix}
    \xrightarrow{\text{R}_{2} - \text{R}_{1}}
    \begin{pmatrix}
    1 & 1  &\bigm| & a \\
    0 & -2  &\bigm| & b-a \\
    \end{pmatrix}
    \xrightarrow{\frac{\text{R}_{3}}{-2}}
    $
    <br><br>
    $
    \begin{pmatrix}
    1 & 1  &\bigm| & a \\
    0 & 1  &\bigm| & -\frac{b-a}{2} \\
    \end{pmatrix}
    \xrightarrow{\text{R}_{1} - \text{R}_{2}}
    \begin{pmatrix}
    1 & 0  &\bigm| & \frac{b+a}{2} \\
    0 & 1  &\bigm| & -\frac{b-a}{2} \\
    \end{pmatrix}
$
<br><br> Therefore, it is a span<br><br>
b.<br><br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br><br>
<br><br> 1.)<br><br>
$
\textbf{x} \begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix} +
\textbf{y} \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} + \textbf{z} \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}{bmatrix}  =
\begin{bmatrix} a \\ b \\ c \end{bmatrix} \\
$
<br><br> 2.) <br><br>
$
    \begin{pmatrix}
    1 & 0 & 1 &\bigm| & a \\
    1 & 1 & 0 &\bigm| & b \\
    0 & 1 & 1 &\bigm| & c \\
    \end{pmatrix}
    \xrightarrow{\text{R}_{2} - \text{R}_{1}}
    \begin{pmatrix}
    1 & 0 & 1 &\bigm| & a \\
    0 & 1 & -1 &\bigm| & b - a\\
    0 & 1 & 1 &\bigm| & c \\
    \end{pmatrix}
    \xrightarrow{\text{R}_{3} - \text{R}_{2}}
    \begin{pmatrix}
    1 & 0 & 1 &\bigm| & a \\
    0 & 1 & -1 &\bigm| & b - a\\
    0 & 0 & 2 &\bigm| & c - b - a\\
    \end{pmatrix}
    \xrightarrow{\frac{\text{R}_{3}}{2}}{\text{R}_{2} + \text{R}_{3}}
    \begin{pmatrix}
    1 & 0 & 1 &\bigm| & a \\
    0 & 1 & 0 &\bigm| & \frac{c + b - 3a}{2}\\
    0 & 0 & 1 &\bigm| & \frac{c - b - a}{2}\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{1} - \text{R}_{3}}
    \begin{pmatrix}
    1 & 0 & 0 &\bigm| & \frac{c - b + a}{2} \\
    0 & 1 & 0 &\bigm| & \frac{c + b - 3a}{2}\\
    0 & 0 & 1 &\bigm| & \frac{c - b - a}{2}\\
    \end{pmatrix}
    $
    <br><br> Therefore, it is a span <br>
    C.)<br><br>
    $
    span\begin{pmatrix}
    \begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
    \begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
    \begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
    \end{pmatrix}
    $ <br><br>
     1.)<br><br>
   $
    \textbf{x} \begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix} +
    \textbf{y} \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} + \textbf{z} \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}{bmatrix}  =
    \begin{bmatrix} a \\ b \\ c \end{bmatrix} \\
$
<br><br> 2.) <br><br>
$
    \begin{pmatrix}
    1 & 0 & 1 &\bigm| & a \\
    1 & 1 & 0 &\bigm| & b \\
    0 & 1 & 1 &\bigm| & c \\
    \end{pmatrix}
    \xrightarrow{\text{R}_{2} - \text{R}_{1}}
    \begin{pmatrix}
    1 & 0 & 1 &\bigm| & a \\
    0 & 1 & -1 &\bigm| & b - a\\
    0 & 1 & 1 &\bigm| & c \\
    \end{pmatrix}
    \xrightarrow{\text{R}_{3} - \text{R}_{2}}
    \begin{pmatrix}
    1 & 0 & 1 &\bigm| & a \\
    0 & 1 & -1 &\bigm| & b - a\\
    0 & 0 & 2 &\bigm| & c - b - a\\
    \end{pmatrix}
    \xrightarrow{\frac{\text{R}_{3}}{2}}{\text{R}_{2} + \text{R}_{3}}
    \begin{pmatrix}
    1 & 0 & 1 &\bigm| & a \\
    0 & 1 & 0 &\bigm| & \frac{c + b - 3a}{2}\\
    0 & 0 & 1 &\bigm| & \frac{c - b - a}{2}\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{1} - \text{R}_{3}}
    \begin{pmatrix}
    1 & 0 & 0 &\bigm| & \frac{c - b + a}{2} \\
    0 & 1 & 0 &\bigm| & \frac{c + b - 3a}{2}\\
    0 & 0 & 1 &\bigm| & \frac{c - b - a}{2}\\
    \end{pmatrix}
    $
    <br><br> Therefore, it is a span


---

8. Show that the following vectors are linearly independent:<br>
a. <br>
$\begin{equation}
\begin{bmatrix} 3 \\ -1 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} -1 \\ 2 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 1 \\ 1 \\ 3 \\ 1 \end{bmatrix}
\begin{bmatrix} -1 \\ -1 \\ 1 \\ 3 \end{bmatrix}
\end{equation}$
b. <br>
$\begin{equation}
\begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 0 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 4 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\end{equation}$
<br>
c. <br>
$\begin{equation}
\begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix}
\begin{bmatrix} -1 \\ 1 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 1 \\ 0 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 0 \\ 1 \\ -1 \\ 1 \end{bmatrix}
\end{equation}$

8.<br><br>
Show that the following vectors are linearly independent:<br><br>
a. <br><br>
$
\begin{equation}
\begin{bmatrix} 3 \\ -1 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} -1 \\ 2 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 1 \\ 1 \\ 3 \\ 1 \end{bmatrix}
\begin{bmatrix} -1 \\ -1 \\ 1 \\ 3 \end{bmatrix}
\end{equation} $
<br><br> First transform it into a reduced row echelon <br><br>
$
    \begin{pmatrix}
    3 & -1 & 1 & -1 \\
    -1 & 2 & 1 & -1 \\
    1 & 1 & 3 & 1 \\
    -1 & -1 & 1 & 3\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{1} \leftrightarrow \text{R}_{3}}
    \begin{pmatrix}
    1 & 1 & 3 & 1 \\
    -1 & 2 & 1 & -1 \\
    3 & -1 & 1 & -1 \\
    -1 & -1 & 1 & 3\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{2} + \text{R}_{1}}
    $
    <br><br>
    $
    \begin{pmatrix}
    1 & 1 & 3 & 1 \\
    0 & 3 & 4 & 0 \\
    3 & -1 & 1 & -1 \\
    -1 & -1 & 1 & 3\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{3} - 3\text{R}_{1}}
    \begin{pmatrix}
    1 & 1 & 3 & 1 \\
    0 & 3 & 4 & 0 \\
    0 & -4 & -8 & -4 \\
    -1 & -1 & 1 & 3\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{4} + \text{R}_{1}}
    $
    <br><br>
    $
    \begin{pmatrix}
    1 & 1 & 3 & 1 \\
    0 & 3 & 4 & 0 \\
    0 & -4 & -8 & -4 \\
    0 & 0 & 4 & 4\\
    \end{pmatrix}
    \xrightarrow[\frac{1}{4}\text{R}_{3}]{\frac{1}{4}\text{R}_{4}}
    \begin{pmatrix}
    1 & 1 & 3 & 1 \\
    0 & 3 & 4 & 0 \\
    0 & -1 & -2 & -1 \\
    0 & 0 & 1 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{1} + \text{R}_{3}}
    $
    <br><br>
    $
    \begin{pmatrix}
    1 & 0 & 1 & 0 \\
    0 & 3 & 4 & 0 \\
    0 & -1 & -2 & -1 \\
    0 & 0 & 1 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{3} + \text{R}_{4}}
    \begin{pmatrix}
    1 & 0 & 1 & 0 \\
    0 & 3 & 4 & 0 \\
    0 & -1 & -1 & 0 \\
    0 & 0 & 1 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{2} + 3\text{R}_{3}}
    $
    <br><br>
    $
    \begin{pmatrix}
    1 & 0 & 1 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & -1 & -1 & 0 \\
    0 & 0 & 1 & 1\\
    \end{pmatrix}
    \xrightarrow[-\text{R}_{3}]{\text{R}_{1} - \text{R}_{2}}
    \begin{pmatrix}
    1 & 0 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 1 & 1 & 0 \\
    0 & 0 & 1 & 1\\
    \end{pmatrix}
    \xrightarrow[\text{R}_{3} - \text{R}_{2}]{\text{R}_{4} - \text{R}_{2}}
    $
    <br><br>
    $
    \begin{pmatrix}
    1 & 0 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 0 & 1\\
    \end{pmatrix}
$ <br><br>
Explaination:
<br>
Based on the solution, it doesn't appear to be linearly dependent or fit the conditions for it. Furthermore, it is also a reduced row echelon, thus it is a linearly independent.
<br><br>


b. <br>
$
\begin{equation}
\begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 0 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 4 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\end{equation}
$
<br><br>
Transform to a reduced row echelon <br><br>
$
    \begin{pmatrix}
    0 & 0 & 0 & 4 \\
    0 & 0 & 3 & 3 \\
    0 & 2 & 2 & 2 \\
    1 & 1 & 1 & 1\\
    \end{pmatrix}
    \xrightarrow[\text{R}_{1} \leftrightarrow \text{R}_{4}]{\text{R}_{2} \leftrightarrow \text{R}_{3}}
    \begin{pmatrix}
    1 & 1 & 1 & 1 \\
    0 & 2 & 2 & 2 \\
    0 & 0 & 3 & 3 \\
    0 & 0 & 0 & 4 \\
    \end{pmatrix}
    \xrightarrow[\frac{1}{2}\text{R}_{2}]{\frac{1}{3}\text{R}_{3}}
    $
    <br><br>
    $
    \begin{pmatrix}
    1 & 1 & 1 & 1 \\
    0 & 1 & 1 & 1 \\
    0 & 0 & 1 & 1 \\
    0 & 0 & 0 & 4 \\
    \end{pmatrix}
    \xrightarrow[\frac{1}{4}\text{R}_{4}]{\text{R}_{1} - \text{R}_{2}}
    \begin{pmatrix}
    1 & 0 & 0 & 0 \\
    0 & 1 & 1 & 1 \\
    0 & 0 & 1 & 1 \\
    0 & 0 & 0 & 1 \\
    \end{pmatrix}
    \xrightarrow[\text{R}_{2} - \text{R}_{3}]{\text{R}_{3} - \text{R}_{4}}
    $
    <br><br>
    $
    \begin{pmatrix}
    1 & 0 & 0 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 0 & 0 & 1 \\
    \end{pmatrix}
    $<br><br>
    Explaination:
    <br>
    Based on the solution, it is a reduced row echelon. However, it does not appear to be linearly dependent or fit the conditions to be one. Thus, the vectors are linearly independent <br>
c. <br>
$
\begin{equation}
\begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix}
\begin{bmatrix} -1 \\ 1 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 1 \\ 0 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 0 \\ 1 \\ -1 \\ 1 \end{bmatrix}
\end{equation}
$
<br><br>
Transform it into a reduced row echelon <br><br>
$
    \begin{pmatrix}
    1 & -1 & 1 & 0 \\
    -1 & 1 & 0 & 1 \\
    1 & 0 & 1 & -1 \\
    0 & 1 & -1 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{2} + \text{R}_{3}}
    \begin{pmatrix}
    1 & -1 & 1 & 0 \\
    0 & 1 & 1 & 0 \\
    1 & 0 & 1 & -1 \\
    0 & 1 & -1 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{3} + \text{R}_{4}}
    $
    <br><br>
    $
    \begin{pmatrix}
    1 & -1 & 1 & 0 \\
    0 & 1 & 1 & 0 \\
    1 & 1 & 0 & 0 \\
    0 & 1 & -1 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{4} + \text{R}_{1}}
    \begin{pmatrix}
    1 & -1 & 1 & 0 \\
    0 & 1 & 1 & 0 \\
    1 & 1 & 0 & 0 \\
    1 & 0 & 0 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{3} - \text{R}_{1}}
    $
    <br><br>
    $
    \begin{pmatrix}
    1 & -1 & 1 & 0 \\
    0 & 1 & 1 & 0 \\
    0 & 2 & -1 & 0 \\
    1 & 0 & 0 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{3} + \text{R}_{2}}
    $<br><br>
    $
    \begin{pmatrix}
    1 & -1 & 1 & 0 \\
    0 & 1 & 1 & 0 \\
    0 & 3 & 0 & 0 \\
    1 & 0 & 0 & 1\\
    \end{pmatrix}
    \xrightarrow{\frac{1}{3}\text{R}_{3}}
    \begin{pmatrix}
    1 & -1 & 1 & 0 \\
    0 & 1 & 1 & 0 \\
    0 & 1 & 0 & 0 \\
    1 & 0 & 0 & 1\\
    \end{pmatrix}
    \xrightarrow[\text{R}_{2} - \text{R}_{3}]{\text{R}_{1} + \text{R}_{3}}
    $
    <br><br>
    $
    \begin{pmatrix}
    1 & 0 & 1 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 1 & 0 & 0 \\
    1 & 0 & 0 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{1} - \text{R}_{2}}
    \begin{pmatrix}
    1 & 0 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 1 & 0 & 0 \\
    1 & 0 & 0 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{4} - \text{R}_{1}}
    $
    <br><br>
    $
    \begin{pmatrix}
    1 & 0 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 0 & 1\\
    \end{pmatrix}
$


$\text{ Explaination:}$
$
\begin{equation}
\boxed{\text{Based on the solution, it is a reduced row echelon. However, it does not appear to be linearly dependent or fit the conditions to be one. Thus, the vectors are linearly independent}}
\end{equation}
$
